project:
  type: website

website:
  title: ✨ Enchanted Stitches
  favicon: /images/logo.png
  twitter-card: true
  open-graph:
    site-name: "✨ Enchanted Stitches"
    locale: en_US
  site-url: https://enchanted-st.netlify.app
        

format:
  html:
    page-layout: full
    theme:
      light: [cosmo, style/custom.scss]
    toc: true
    code-copy: true
    code-overflow: wrap

execute:
  freeze: auto
